name: 'Kustomize build input'
description: 'Build kustomize and compare with same build from different branch'
inputs:
  kustomization-location:
    description: 'Directory path of the root kustomization.yaml. Default is root of repository.'
    required: true
    default: './'

  compare-branch-name:
    description: 'The name of the branch that want to compare. Usually is the name of the branch you branched of'
    required: true
    default: 'master'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kustomization-location }}
    - ${{ inputs.compare-branch-name }}